#!/usr/bin/php
<?php

define('SYSTEM_PLAYER', '/usr/bin/afplay');
define('SYSTEM_PROCESS_KILLER', '/usr/bin/killall');
define('DEBUG_MODE', true);
require_once('common/Utility.class');

use \Utility as Util;

### START OF MAIN ###

$app = new MUG_Player();
$app->run();

### END OF MAIN ###


class MUG_Player
{

   const LOG_ENABLED = true;
   public $shortArgs;
   public $longArgs;
   public $commands;
   public $scriptName;
   public $elapsedTime;
   public $startTime;
   public $endTime;
   public $jsonFile;
   public $db;
   private $current;

   public function __construct()
   {
      
       $this->startTime  = microtime(true);
       $this->scriptName = basename(__FILE__);
       $this->shortArgs = "p:b";
       $this->logArgs   = ["play:", "build", "stop"];

       $this->jsonFile = sprintf("%s/.mugplayer.json", getenv('HOME'));

       if (file_exists($this->jsonFile))
           $this->load();

       if (!$this->commands  = Util::getArgs($this->shortArgs, $this->logArgs))
          $this->syntax();
   }
   
   public function syntax()
   {
      printf("%s --build    ... builds the ~/Users/%s/.music.json database\n", $this->scriptName, getenv("USER"));
      printf("%s --play tag ... finds music by tag and plays it\n", $this->scriptName);
      exit;
   }

   public function run()
   {
      foreach($this->commands as $cmd => $options)
      {
         $this->log("Process $cmd with $options");

         switch ($cmd)
         {
            case 'build' : $this->build($options); break;
            case 'play'  : $this->play($options); break;
            case 'stop'  : $this->stop($options); break;
            default : $this->syntax();
         }
  
      }
   }

   private function load()
   {
      $this->db  = json_decode(file_get_contents($this->jsonFile), true);
      $jsonError = json_last_error();

      if ($jsonError != JSON_ERROR_NONE)
      {
          $this->log("Cannot load {$this->jsonFile}. Error code: $jsonError"); 
          die();
      }
   }

   private function play($tag)
   {

      $matches = [];
      foreach($this->db as $this->current => $entry)
      {
          if (preg_match("/$tag/i", $entry['path']))
          {
              $matches[] = $entry;
              break;
          }
      }

      $matchCnt = count($matches);
      // Only one MP3 matches so play it
      if ($matchCnt == 1)
      {
         $this->playSong($matches[0]['path']);    

      } else if($matchCnt > 1) {
 
         $this->log("Show list");
         $this->log($matches);
        
      } else {
         $this->log("No match found.");
      }

   }

   private function playSong($path)
   {
     // Stop the last song
     $this->stop();
     $cmd = sprintf("%s -q 1 \"%s\" &", SYSTEM_PLAYER, $path);
     $this->log("Run $cmd");
     proc_close(proc_open($cmd, [], $junk));

     $this->db[$this->current]['stats']['count']++;
     $this->db[$this->current]['stats']['last_played'] = date('m/d/Y h:i:s');

     $this->write();

     $this->log($this->db[$this->current]);

   }

   private function stop($options = null)
   {
      
      $descriptorspec = [ 
                           0 => ["pipe", "r"],  // STDIN
                           1 => ["pipe", "w"],  // STDOUT
                           2 => ["pipe", "w"],  // STDERR

                        ];

      $cwd = getcwd();
      $env = null;
      $cmd = sprintf("%s afplay", SYSTEM_PROCESS_KILLER);
      $this->log("Run $cmd");
      $process = proc_open($cmd, $descriptorspec, $pipes, $cwd, $env);

      if (is_resource($process))
      {
          proc_close($process);
      }

   }

   private function build($options)
   {
      $this->homeDir = getenv("HOME");
      $this->log("Starting to build at " . $this->homeDir);

      if (!$list = Util::findFiles($this->homeDir, '/^.+\.mp3$/i'))
      {
          $this->log("No MP3 files found in {$this->homeDir}");
          return false;
      }
 

      echo "\nTotal files: " . count($list) . "\n";
      $this->log("Total time spent: " . $this->elapsed() . " seconds");

      $data = [];
      foreach($list as $file)
      {
         $data[] = ['path' => $file, 'tags' => []]; 
      }

      $this->db = $data;
      $this->write();

   }

   private function write()
   {
      $json = json_encode($this->db, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
      file_put_contents($this->jsonFile, $json);
   }

   private function elapsed()
   {
      return microtime(true) - $this->startTime;
   }
 

   private function log($x)
   {

      if (self::LOG_ENABLED == false)
         return false;

      if (is_array($x) || is_object($x))
      {
          $x = print_r($x, true);
      }

      $logEntry = sprintf("%s: %s - %s\n", date('m/d/y h:i:s'), getmypid(), $x);
      echo $logEntry;
      return true;

   }

} // End of MUG_Player class
