#!/usr/bin/php
<?php
/*
 *  mugplayer is a command-line tool for playing songs (MP3) and playlists
 *  To learn more about this tool, visit: https://macuser.group YouTube channel
 *  Copyright (c) 2021 by Mohammed Kabir (kabir@macuser.group)
 *  Published as an open source software under the MIT license.
 */

mb_internal_encoding("utf-8");
define('SYSTEM_PLAYER', '/usr/bin/afplay');
define('SYSTEM_KILLALL_BINARY', '/usr/bin/killall');
define('SYSTEM_KILL_BINARY', '/bin/kill');
define('SYSTEM_AT_SCHEDULER', '/usr/bin/at');
define('DEBUG_MODE', getenv('USER') == "kabir" ? true : false);
require_once('common/Utility.class');

use \Utility as Util;

function __($text) { return $text; }

/*
 * Start of main()
 */
$app = new MUG_Player();
$app->run();

/* end of main */

class MUG_Player
{
   const LOG_ENABLED = true;
   public $id = 'mugplayer';
   public $shortArgs;
   public $longArgs;
   public $commands;
   public $scriptName;
   public $elapsedTime;
   public $startTime;
   public $endTime;
   public $jsonFile;
   public $db;
   private $currentSong;
   private $chosenTrack = null;
   private $playlistPIDFile;
   private $homeDir;
   private $timezone;
   private $sleepTime = 0;
   private $currentPlaylist = null;
   private $currentPlaylistSlug = null;


   public function __construct()
   {
       $this->homeDir    = getenv("HOME");
       $this->setTimezone();
       $this->startTime  = microtime(true);
       $this->scriptName = basename(__FILE__);
       $this->shortArgs  = "p:b";
       $this->logArgs    = ["play:", "loop:", "at:", "build", "stop", "stats", "dups", "find:", "search:", "create:", "add:", "view:", "delete:"];

       $this->jsonFile        = sprintf("%s/.mugplayer.json", $this->homeDir);
       $this->playlistPIDFile = sprintf("%s/.mugplayer.playlist.pid", $this->homeDir);

       if (file_exists($this->jsonFile))
           $this->load();

      if (!empty($this->db['current']['song']))
          $this->currentSong = $this->db['current']['song'];
      
      if (!empty($this->db['current']['playlist']))
      {
         $this->currentPlaylist     = $this->db['current']['playlist']['name']; 
         $this->currentPlaylistSlug = $this->db['current']['playlist']['slug']; 
      }

       if (!$this->commands  = Util::getArgs($this->shortArgs, $this->logArgs))
          $this->syntax();
   }
   
   public function syntax()
   {
      $n = $this->scriptName;
      printf("%s --build                     ... builds the %s/.mugplayer.json database\n", $n, $this->homeDir);
      printf("%s --play title|tag|playlist   ... plays song by title or tag or entire playlist it\n", $n);
      printf("%s --loop title|tag|playlist   ... plays song by title or tag or entire playlist until stopped\n", $n);
      printf("%s --at hh:mm:ss  tag|playlist ... play the song or playlist at hh:mm:ss\n", $n);
      printf("%s --stop                      ... stop playing\n", $n);
      printf("%s --stats                     ... show stats\n", $n);
      printf("%s --dups                      ... show dups\n", $n);
      printf("%s --create name               ... create a playlist\n", $n);
      printf("%s --view name                 ... vew a playlist\n", $n);
      printf("%s --add title <list>          ... add title to current or named playlist\n", $n);
      printf("%s --del title <list>          ... delete title from current or named playlist\n", $n);
      exit;
   }

   public function run()
   {
      foreach($this->commands as $cmd => $options)
      {
         switch ($cmd)
         {
            case 'build'  : $this->build($options); break;
            case 'dups'   : $this->build(['write' => false]); break;
            case 'play'   : $this->play($options); break;
            case 'loop'   : $this->play($options, true); break;
            case 'find'   : $this->find($options); break;
            case 'search' : $this->find($options); break;
            case 'create' : $this->create($options); break;
            case 'add'    : $this->add($options); break;
            case 'delete' : $this->delete($options); break;
            case 'view'   : $this->view($options); break;
            case 'stop'   : $this->stop($options); break;
            case 'stats'  : $this->stats(); break;
            case 'at'     : $this->at($options); break;
            default       : $this->syntax();
         }
      }

      $this->die();
   }

   private function stats($show = true)
   {
      $stats = [];
      foreach($this->db as $i => $entry)
      {
         if (!empty($entry['stats']))
         {
            $stats[] = [
                          'id'     => $i,
                          'title'  => !empty($entry['meta']['title']) ? $entry['meta']['title'] : basename($entry['path']),
                          'count'  => $entry['stats']['count'],
                          'last_played' => $entry['stats']['last_played']
                       ];
         }
      }

      if (!$stats)
          $this->die(__('No stats found.'));

      $count = array_column($stats, 'count');
      array_multisort($count, SORT_DESC, $stats);

      if (!$show)
          return $stats;

      printf("%s %-60s %s %13s\n", __('No.'), __('Title'), __('Played'), __('Last Played'));
    

      foreach($stats as $i => $r)
      {
         $title = preg_replace("/\.mp3$/i", '', $r['title']);
         $title = mb_substr($title, 0, 60, "utf-8");
         printf("%-3d %s %4d %25s\n", $i+1, Util::mb_str_pad($title, 60, '.'), $r['count'], $r['last_played']);
      }

      return $stats;
   }

   private function load()
   {
      $this->db  = json_decode(file_get_contents($this->jsonFile), true);
      $jsonError = json_last_error();

      if ($jsonError != JSON_ERROR_NONE)
      {
          $this->log("Cannot load {$this->jsonFile}. Error code: $jsonError"); 
          die();
      }
   }

   private function play($tag, $loop = false)
   {
      $this->getChosenTrack($tag);
      $matches  = $this->findSong($tag);
      $matchCnt = count($matches);

      // Only one MP3 matches so play it
      if ($matchCnt == 1)
      {
         $song          = $matches[0]['entry'];
         $this->currentSong = $song['hash']; 
         return (!$loop) ? $this->playSong($song['path']) : $this->playLoop($song, $loop); 

      // Hmm, we have more than one match so..
      } else if($matchCnt > 1) {
 
         // If the user hasn't selected one using #n, 
         // show the list of matches 
         if (is_null($this->chosenTrack))
             return $this->list($matches);

         // User selected #n track so lets play it   
         $song          = $matches[$this->chosenTrack]['entry'];
         $this->currentSong = $song['hash']; 
         return (!$loop) ? $this->playSong($song['path']) : $this->playLoop($song, $loop);
      } 
      
      // Hmm, no match for MP3, so lets find out if a
      // playlist matches the tag
      if (!$matches = $this->findPlaylist($tag))
         $this->log("No song or playlist found for: $tag.");

      $matchCnt = count($matches);

      // Only one MP3 matches so play it
      if ($matchCnt == 1)
          return $this->playList($matches[0], $loop);
 
      // If more than one playlist matches the tag and the
      // user hasn't chosen the playlist using #n, show list
      if (is_null($this->chosenTrack))
            return $this->list($matches);

      // User chose a playlist using #n so lets play it
      return $this->playList($matches[$this->chosenTrack], $loop);    
   }

   private function find($tag)
   {
      if ($matches = $this->findSong($tag))
          return $this->log("No match found.");

      $this->list($matches);
   }

   private function findPlaylist($tag)
   {
      $matches = [];

      if (preg_match("/^top\-?(\d+)$/i", $tag, $options))
      {
          $max = $options[1];
          $this->chosenPlayList = $tag;
          $stats = $this->stats(false);
          $list = count($stats) > $max ? array_slice($stats, 0, $max) : $stats;
          $matches[] = ['name' => $tag, 'list' => $list, 'count' => count($list)];
          return $matches;
      }

      // Find playlist in DB
      if (!$playlists = $this->db['playlists'])
          return $matches;

      foreach($playlists as $p)
      {
         $name = $p['name'];
         if (preg_match("/^$tag$/i", $name)) 
         {
             foreach($p['songs'] as $hash => $info)
             {
                $list[] = ['id' => $hash, 'title' => $info['meta']['title']];
             }
             $matches[] = ['name' => $name, 'list' => $list, 'count' => count($list)];
             return $matches;   
         }
      }


      return false;
   }

   private function findSong($tag)
   {
      $matches = [];

      foreach($this->db as $this->currentSong => $entry)
      {
          if (preg_match("/$tag/mi", $entry['meta']['title']))
          {
              $matches[] = ['entry' => $entry, 'index' => $this->currentSong];

          } elseif (preg_match("/$tag/i", $entry['path'])) {

              $matches[] = ['entry' => $entry, 'index' => $this->currentSong];
          }
      }

      return $matches;
   }

   private function getChosenTrack($tag)
   {
      $this->chosenTrack = null;

      $args = Util::getRawArgs();

      foreach($args as $thisArg)
      if (preg_match("/^#(\d)+$/", $thisArg, $matches))
      {
         $this->chosenTrack = $matches[1] - 1;
         return $this->chosenTrack;
      }
         
      return false;
   }

   private function list($list)
   {
      foreach($list as $i => $r)
      {
         $entry = $r['entry'];
         $index = $r['index'];
         $meta  = $entry['meta'];
         $title = $meta['title'];
         printf("%4d %s\n", $i+1, $title);
      }
   }

   private function playSong($path)
   {
      // Stop playing 
      $this->stop();

      $cmd = sprintf("%s -q 1 \"%s\" &", SYSTEM_PLAYER, $path);
      $process = proc_open($cmd, [], $junk);

      if(is_resource($process))
      {
         $status = proc_get_status($process);
         $pid = $status['pid'];
         proc_close($process);
      }

      $this->db[$this->currentSong]['stats']['count']++;
      $this->db[$this->currentSong]['stats']['last_played'] = date('m/d/Y h:i:s');
      $this->db['current']['song'] = $this->currentSong;

      $this->write();
      $this->close();
   }

   private function playList($pl, $loop = false)
   {
      // Stop playing
      $this->stop();

      $name = $pl['name'];

      $this->log("Play $name playlist loop: $loop");
      $scriptFile = sprintf("%s/.%s-playlist-%s.sh", sys_get_temp_dir(), $this->id, $pl['name']);
      $list   = $pl['list'];
      $script  = "#!/bin/bash\n";
      $script .= "echo $$ > {$this->playlistPIDFile}\n\n";

      // If this playlist needs to be played at a future time
      // insert sleep delay
      if ($this->sleepTime)
      {
         $script .= "sleep {$this->sleepTime};\n";
      }

      $script .= "# Playlist: $name\n";
      $script .= "# Created by {$this->id} at " . date('m/d/y h:i:s A T') . "\n";
      $script .= "# YouTube channel: https://macuser.group\n";
      $script .= "##########################################\n\n";

      $timeFlag = (DEBUG_MODE) ? '-t 10' : '';

      if ($loop)
      {
         $script .= "while : \n";
         $script .= "do\n";
      }
         

      foreach($list as $i => $r)
      {
         $id      = $r['id'];
         $title   = $r['title'];
         $entry   = $this->db[$id];
         $path    = $entry['path'];
         $cnt     = $i + 1;
         $cmd     = sprintf("%s %s -q 1 \"%s\";", SYSTEM_PLAYER, $timeFlag, $path);
         $script .= "# Play song #{$cnt}: $title  ($id)\n";

         if (DEBUG_MODE)
             $script .= sprintf("/usr/bin/osascript -e 'display notification \"Playing: $title\"'\n");

         $script .= $cmd . "\n\n";
      }

      if (DEBUG_MODE && !$loop)
         $script .= sprintf("/usr/bin/osascript -e 'display notification \"Playlist: $name completed\"'\n");

      if ($loop)
      {
          $script .= "\ndone\n";
      }

      $script .= "# Remove the playlist shell script\n";
      $script .= '/bin/rm -- "$0"' . "\n";

      file_put_contents($scriptFile, $script);

      $this->log("Playing playlist: $name");
      chmod($scriptFile, 0700);
      $this->_exec($scriptFile);
      $this->close();
   
   }

   private function playLoop($entry)
   {
        $pl = [];

        $pl['name']   = 'loop';
        $pl['list'][] = [  
                         'id'     => $entry['hash'],
                         'title'  => $entry['meta']['title'],
                         'count'  => 1
                        ];

        $pl['count'] = 1;
        $this->playList($pl, true);
   }

   private function stop($options = null)
   {
      $descriptorspec = [ 
                           0 => ["pipe", "r"],  // STDIN
                           1 => ["pipe", "w"],  // STDOUT
                           2 => ["pipe", "w"],  // STDERR
                        ];
      $cwd = getcwd();
      $env = null;
      
      $playlistPID = file_exists($this->playlistPIDFile) ? file_get_contents($this->playlistPIDFile) : null;

      if ($playlistPID)
      {
         $cmd = sprintf("%s -9 %s", SYSTEM_KILL_BINARY, $playlistPID);
         $process = proc_open($cmd, $descriptorspec, $pipes, $cwd, $env);  

          if (is_resource($process))
          {
             unlink($this->playlistPIDFile);
             proc_close($process);
          } 
      }

      $cmd = sprintf("%s afplay", SYSTEM_KILLALL_BINARY);
      $process = proc_open($cmd, $descriptorspec, $pipes, $cwd, $env);

      if (is_resource($process))
          proc_close($process);

      return true;
   }

   private function build($options)
   {     
      $this->log("Looking for songs in dir: " . $this->homeDir);

      if (!$list = Util::findFiles($this->homeDir, '/^.+\.mp3$/i'))
      {
          $this->log("No songs found in {$this->homeDir}");
          return false;
      }
 
      echo "\nTotal files: " . count($list) . "\n";
      $this->log("Total time spent: " . $this->elapsed() . " seconds");

      $data = [];
      $dups = [];
      foreach($list as $file)
      {
         $key = Util::getFileHash($file);

         if (!empty($data[$key]))
         {
            $existing = $data[$key]['path'];
            $dups[$key]['original'] = $existing;
            $dups[$key]['dups'][]   = $file;
         } else
            $data[$key] = ['path' => $file, 'hash' => $key, 'meta' => $this->getMeta($file)]; 
      }

      if (!empty($dups))
          return $this->dups($dups);

      if ($options['write'] == false)
          return false;

      $this->db = $data;
      $this->write();
      
      return true;
   }

   private function dups($list)
   {
       $cmd = Util::getLastArg();
       
       $cmd = preg_match("/(remove|delete|rm)/i", $cmd) ? 'delete' : null;
       $output = null;

       if ($cmd == "delete")
       {
          $output  = "#!/bin/bash\n#\n#\n";
          $output .= "# Please run the remove-dup.sh script only if you wish to delete all the duplicates\n";
          $output .= "echo \"This will delete duplicate songs (MP3) from your storage\"\n";
          $output .= "echo \"You have ~10 seconds to press control+c to break out\"\n";
          $output .= "sleep 15\n";
         
       }

       foreach($list as $key => $files)
       {
          $original = $files['original'];

          $output .= "# Original: $original\n";
          foreach($files['dups'] as $duplicate)
          {
              if ($cmd == 'delete')
                 $output .= "/bin/rm -f \"$duplicate\";\n";
              else
                 $output .= "# Duplicate: $duplicate\n";
          }

          $output .= "\n"; 
       }

       // echo $output;
       if ($cmd == "delete")
       {
         file_put_contents("remove-dups.sh", $output);
         chmod("remove-dups.sh", 0700);
         echo __("See remove-dup.sh in the current directory for details\n");
       } else {
          echo $output;
       }

   }

   private function at($when)
   {
      $tag = Util::getLastArg();
      $now  = time();
      $sch  = strtotime("today $when");
   
      if ($sch < $now)
          $sch = strtotime("+1 day $when");
      
      $sleep = $sch - time();
      $start = date('m/d/y h:i A T', $sch);
      $this->log("Scheduling $tag at $start  sleep: $sleep seconds");

      $this->sleepTime = $sleep;
      $this->play($tag);
   }

   private function create($name)
   {
      $slug      = Util::createSlug($name);
      $playlists = $this->db['playlists'];

      if (!empty($playlists[$slug]))
      {
         $this->log("Already exists: $name slug: $slug");
         return false;
      } 

      $this->log("Create a playlist called $name  slug: $slug");
      $newPlayList                  = [
                                        'name'    => $name, 
                                        'created' => date('m/d/y h:i:s'),
                                        'songs'   => [],
                                        'play-count' => 0
                                      ];

      $this->currentPlaylist        = $name;
      $this->currentPlaylistSlug    = $slug;
      $this->db['playlists'][$slug] = $newPlayList;
      $this->db['current']['playlist']['name'] = $name;
      $this->db['current']['playlist']['slug'] = $slug;
      $this->write();

      return $slug;
   }

   private function add($tag)
   {
      if (!$chosen = $this->getChosenSong($tag))
         return false;

      $str = Util::getLastArg();

      $playlist = preg_match("/^#\d+$/", $str) ? $this->currentPlaylist : $str;

      if (!$slug = $this->isExistingPlaylist($playlist))
      {
          $confirm = Util::prompt("Create a new playlist: $playlist [Yes / No] ? ",["yes", "no"]);

         if ($confirm != 'YES')
             return false;
   
         if (!$slug = $this->create($playlist))
             return false;
      }

      $song = $chosen['entry'];
      $hash = $song['hash'];
      $title = $song['meta']['title'];

      if (!empty($this->db['playlists'][$slug]['songs'][$hash]))
      {
         $this->log("$title already exists in the $playlist playlist!");
         return false;
      }

      // Add song to playlist
      $this->log("Added $title to $playlist playlist.");
      $this->db['playlists'][$slug]['songs'][$hash] = ['added' => time()];

      // Write database
      $this->write();
   }

   private function getChosenSong($tag)
   {
      $this->getChosenTrack($tag);
      $matches  = $this->findSong($tag);
     
      if (!$matchCnt = count($matches))
      {
         $this->log("No song matched for: $tag");
         return false;
      }

      // $this->log("$tag matched $matchCnt songs");
      if ($matchCnt == 1)
      {
          $song = $matches[0];

      } else {

         // If the user hasn't selected one using #n, 
         // show the list of matches 
         if (is_null($this->chosenTrack))
             return $this->list($matches);

         // User selected #n track
         $song  = $matches[$this->chosenTrack];

      }

      return $song;
   }

   private function delete($name)
   {
      if (!$slug = $this->isExistingPlaylist($name))
      {
          $this->log("Cannot find $name playlist.");
          return false;
      }

      $confirm = Util::prompt("Please type 'yes' to delete or 'no' to abort: ",["yes", "no"]);

      if ($confirm != 'YES')
          return false;


      $this->log("Delete $name playlist");
      unset($this->db["playlists"][$slug]);
      $this->write();
   }

   private function isExistingPlaylist($name  = null)
   {
      $name = empty($name) ? $this->currentPlaylist : $name;
      $slug = Util::createSlug($name);
      return !empty($this->db['playlists'][$slug]) ? $slug : false;

   }

   private function view($name = null)
   {

       if (!preg_match("/(top\d+|all)/i",strtoupper($name)))
       {
          $slug            = Util::createSlug($name);
          $playlist[$slug] = $this->db['playlists'][$slug]; 
       
       } else {

           $playlist = $this->db['playlists'];
           if (preg_match("/^top\-?(\d+)$/i", $name, $options))
           {
               $max   = $options[1];;
               $stats = $this->stats(false);
               $list  = count($stats) > $max ? array_slice($stats, 0, $max) : $stats;
               $songs = [];
   
               foreach($list as $i => $info)
               {
                  $hash = $info['id'];
                  $songs[$hash] = $this->db[$hash];
               }
   
               $playlist[$name] = ['name' => $name, 'songs' => $songs];
            }
       }
 
       if ($name != 'all' && empty($playlist[$name]))
       {
          $this->log("No playlist found for $name");
          return false;
       }

       foreach($playlist as $slug => $p)
       {
         $name  = $p['name']; 
         $songs = $p['songs'];
         $cnt   = count($songs);

         echo "\nPlaylist: $name has $cnt songs\n";
         $i = 1;

         foreach($songs as $hash => $info)
         {
            $song  = $this->db[$hash];
            $title = preg_replace("/\.mp3$/i", '', $song['meta']['title']);
            $title = mb_substr($title, 0, 60, "utf-8");
            printf("%d %s %d %s\n", $i, Util::mb_str_pad($title, 70, '.'), $song['stats']['count'], $song['last_played']);
            $i++;
         }
       }
   }

   private function write()
   {
      $json = json_encode($this->db, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
      file_put_contents($this->jsonFile, $json);
   }

   private function getMeta($path)
   {
       $title = preg_replace("/\.mp3$/i", '', basename($path));
       $data  = ['title' => $title];

       return $data;
   }

   private function elapsed()
   {
      return microtime(true) - $this->startTime;
   }
 
   private function log($x)
   {
      if (self::LOG_ENABLED == false)
         return false;

      if (is_array($x) || is_object($x))
      {
          $x = print_r($x, true);
      }

      $logEntry = sprintf("%s: %s\n", date('h:i:s'), $x);
      echo $logEntry;
      return true;
   }

   private function _exec($cmd, $bg = true)
   {
      $cwd = getcwd();
      $env = null;

      if ($bg)
          $cmd .= ' &';

      $process = proc_open($cmd, [], $pipes, $cwd, $env);

      if(is_resource($process))
      {
         $status = proc_get_status($process);
         $pid    = $status['pid'];
         proc_close($process);
      }

   }

   private function close()
   {
      // $this->log("Closing this instance.");
      exit;
   }

   private function die($msg = null)
   {
      die($msg); 
   }

   private function setTimezone()
   {
      $this->timezone = Util::getMacOSLocalTimezone();
      date_default_timezone_set ($this->timezone);
   }

} // End of MUG_Player class
