#!/usr/bin/php
<?php

define('SYSTEM_PLAYER', '/usr/bin/afplay');
define('SYSTEM_PROCESS_KILLER', '/usr/bin/killall');
define('DEBUG_MODE', true);
require_once('common/Utility.class');

use \Utility as Util;


function __($text) { return $text; }

### START OF MAIN ###

$app = new MUG_Player();
$app->run();

### END OF MAIN ###

class MUG_Player
{

   const LOG_ENABLED = true;
   public $shortArgs;
   public $longArgs;
   public $commands;
   public $scriptName;
   public $elapsedTime;
   public $startTime;
   public $endTime;
   public $jsonFile;
   public $db;
   private $current;
   private $chosenTrack = null;

   public function __construct()
   {
      
       $this->startTime  = microtime(true);
       $this->scriptName = basename(__FILE__);
       $this->shortArgs = "p:b";
       $this->logArgs   = ["play:", "build", "stop", "stats", "dups", "find:", "search:" ];

       $this->jsonFile = sprintf("%s/.mugplayer.json", getenv('HOME'));

       if (file_exists($this->jsonFile))
           $this->load();

       if (!$this->commands  = Util::getArgs($this->shortArgs, $this->logArgs))
          $this->syntax();
   }
   
   public function syntax()
   {
      printf("%s --build    ... builds the ~/Users/%s/.music.json database\n", $this->scriptName, getenv("USER"));
      printf("%s --play tag ... finds music by tag and plays it\n", $this->scriptName);
      printf("%s --stop     ... stop playing\n", $this->scriptName);
      printf("%s --stats    ... show stats\n", $this->scriptName);
      printf("%s --dups     ... show dups\n", $this->scriptName);
      exit;
   }

   public function run()
   {
      foreach($this->commands as $cmd => $options)
      {
         switch ($cmd)
         {
            case 'build'  : $this->build($options); break;
            case 'dups'   : $this->build(['write' => false]); break;
            case 'play'   : $this->play($options); break;
            case 'find'   : $this->find($options); break;
            case 'search' : $this->find($options); break;
            case 'stop'   : $this->stop($options); break;
            case 'stats'  : $this->stats($options); break;
            default       : $this->syntax();
         }
      }
   }

   private function stats()
   {
      $stats = [];
      foreach($this->db as $i => $entry)
      {
         if (!empty($entry['stats']))
         {
            $stats[] = [
                          'id'    => $i,
                          'name'  => !empty($entry['meta']['title']) ? $entry['meta']['title'] : basename($entry['path']),
                          'count' => $entry['stats']['count'],
                          'last_played' => $entry['stats']['last_played']
                       ];
         }
      }

      if (!$stats)
          $this->die(__('No stats found.'));

      $count = array_column($stats, 'count');
      array_multisort($count, SORT_DESC, $stats);

      printf("%s %-50s %s %18s\n", __('No.'), __('Title'), __('Played'), __('Last Played'));

      foreach($stats as $i => $r)
      {
         $name = preg_replace("/\.mp3$/i", '', $r['name']);
         $name = substr($name, 0, 50);
         printf("%-3d %-50s %2d %30s\n", $i+1, $name, $r['count'], $r['last_played']);
      }
   }

   private function load()
   {
      $this->db  = json_decode(file_get_contents($this->jsonFile), true);
      $jsonError = json_last_error();

      if ($jsonError != JSON_ERROR_NONE)
      {
          $this->log("Cannot load {$this->jsonFile}. Error code: $jsonError"); 
          die();
      }
   }

   private function play($tag)
   {

      $this->getChosenTrack($tag);

      $matches = [];

      foreach($this->db as $this->current => $entry)
      {
          if (preg_match("/$tag/mi", $entry['meta']['title']))
          {
              $matches[] = ['entry' => $entry, 'index' => $this->current];

          } elseif (preg_match("/$tag/i", $entry['path'])) {

              $matches[] = ['entry' => $entry, 'index' => $this->current];
          }
      }

      $matchCnt = count($matches);
      // Only one MP3 matches so play it
      if ($matchCnt == 1)
      {
         $this->current = $matches[0]['entry']['hash']; 
         $this->playSong($matches[0]['entry']['path']);    

      } else if($matchCnt > 1) {
 

         if (is_null($this->chosenTrack))

             $this->list($matches);

         else {

            $this->current = $matches[$this->chosenTrack]['entry']['hash']; 
            $this->playSong($matches[$this->chosenTrack]['entry']['path']);    
         }
        
      } else {
         $this->log("No match found.");
      }
   }

   private function find($tag)
   {

      $matches = [];

      foreach($this->db as $this->current => $entry)
      {
          if (preg_match("/$tag/mi", $entry['meta']['title']))
          {
              $matches[] = ['entry' => $entry, 'index' => $this->current];

          } elseif (preg_match("/$tag/i", $entry['path'])) {

              $matches[] = ['entry' => $entry, 'index' => $this->current];
          }
      }

      if(count($matches) > 0) {
 
         $this->list($matches);
        
      } else {

         $this->log("No match found.");
      }
   }

   private function getChosenTrack($tag)
   {
      $this->chosenTrack = null;

      $tag = Util::getLastArg();

      if (!preg_match("/^#(\d+)$/", $tag, $matches))
         return false;

      if (!$matches)
          return false;

      $this->chosenTrack = $matches[1] - 1;

      return $this->chosenTrack;
   }

   private function list($list)
   {
      foreach($list as $i => $r)
      {
         $entry = $r['entry'];
         $index = $r['index'];
         $meta  = $entry['meta'];
         $title = $meta['title'];
         printf("%4d %s\n", $i+1, $title);
      }
   }

   private function playSong($path)
   {
     // Stop the last song
     $this->stop();

     $cmd = sprintf("%s -q 1 \"%s\" &", SYSTEM_PLAYER, $path);
     proc_close(proc_open($cmd, [], $junk));

     $this->db[$this->current]['stats']['count']++;
     $this->db[$this->current]['stats']['last_played'] = date('m/d/Y h:i:s');

     $this->write();
   }

   private function stop($options = null)
   {
      $descriptorspec = [ 
                           0 => ["pipe", "r"],  // STDIN
                           1 => ["pipe", "w"],  // STDOUT
                           2 => ["pipe", "w"],  // STDERR
                        ];
      $cwd = getcwd();
      $env = null;
      $cmd = sprintf("%s afplay", SYSTEM_PROCESS_KILLER);
      $process = proc_open($cmd, $descriptorspec, $pipes, $cwd, $env);

      if (is_resource($process))
          proc_close($process);
   }

   private function build($options)
   {
      $this->homeDir = getenv("HOME");
      $this->log("Looking for MP3 from dir: " . $this->homeDir);

      if (!$list = Util::findFiles($this->homeDir, '/^.+\.mp3$/i'))
      {
          $this->log("No MP3 files found in {$this->homeDir}");
          return false;
      }
 

      echo "\nTotal files: " . count($list) . "\n";
      $this->log("Total time spent: " . $this->elapsed() . " seconds");

      $data = [];
      $dups = [];
      foreach($list as $file)
      {
   
         $key = Util::getFileHash($file);

         if (!empty($data[$key]))
         {
            $existing = $data[$key]['path'];
            $dups[] = ['original' => $existing, 'duplicate' => $file];
         } else
            $data[$key] = ['path' => $file, 'hash' => $key, 'meta' => $this->getMeta($file)]; 
      }

      if (!empty($dups) && !empty($options) && $options['write'] == false)
      {
          $this->log($dups);
          return false;
      }

      $this->db = $data;
      $this->write();

   }

   private function write()
   {
      $this->log("Writing {$this->jsonFile}");
      $json = json_encode($this->db, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
      file_put_contents($this->jsonFile, $json);
   }

   private function getMeta($path)
   {
       $title = preg_replace("/\.mp3$/i", '', basename($path));
       $data  = ['title' => $title];

       return $data;
   }

   private function elapsed()
   {
      return microtime(true) - $this->startTime;
   }
 

   private function log($x)
   {

      if (self::LOG_ENABLED == false)
         return false;

      if (is_array($x) || is_object($x))
      {
          $x = print_r($x, true);
      }

      $logEntry = sprintf("%s: %s - %s\n", date('m/d/y h:i:s'), getmypid(), $x);
      echo $logEntry;
      return true;

   }

   private function die($msg)
   {
      die($msg); 
   }

} // End of MUG_Player class
